In [1]:
# ----------------------------------------------------------------------------------------------------
# 라이브러리 목록

# 기본 라이브러리 
import pandas as pd

# 개인 라이브러리 
from preparation_for_analysis.show_window import DataVisualizer
from preparation_for_analysis.outlier import OutlierHandler

# pandas 설정
pd.set_option('display.max_rows', None)  # 모든 행 출력
pd.set_option('display.max_columns', None)  # 모든 열 출력

# preparation_for_analysis 설정
visualizer = DataVisualizer(line="=", length=100, start="#")
# ----------------------------------------------------------------------------------------------------

In [2]:
# ----------------------------------------------------------------------------------------------------
# learning 불러오기 
learning = pd.read_csv(
    "C:\\Users\\ssalt\\Documents\\ev_price_predict_project\\data\\train\\A_df\\c_learning\\1_learning.csv",
    sep=",",
    header=0
)

visualizer.show_df_info(title="learning.info", df=learning)
# ----------------------------------------------------------------------------------------------------

====================================================================================================

# Title: learning.info

====================================================================================================

# DataFrame Information:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6747 entries, 0 to 6746
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            6747 non-null   object
 1   Model         6747 non-null   object
 2   Manufacturer  6747 non-null   object
 3   Model_year    6747 non-null   int64
 4   Drivetrain    6747 non-null   object
 5   Warranty      6747 non-null   int64
 6   Accident      6747 non-null   object
 7   Condition     6747 non-null   object
 8   Battery       4311 non-null   float64
 9   Mileage       6747 non-null   int64
 10  Price         6747 non-null   float64
dtypes: float64(2), int64(3), object(6)
memory usage: 579.9+ KB

====================================================================================================

In [3]:
# ----------------------------------------------------------------------------------------------------
# "Battery" 컬럼의 이상치 확인 

# 이상치 인덱스 확인
outliers_idx = []
for (v1, v2, v3, v4, v5, v6, v7), group in learning.groupby([
    "Model", "Manufacturer", "Model_year",
    "Drivetrain", "Warranty", "Accident",
    "Condition"
    ]):

    group_outlier_idx = OutlierHandler(df=group).find_outliers("Battery")

    if group_outlier_idx == []:
        pass
    else:
        outliers_idx.extend(group_outlier_idx)

# 이상치 인덱스 적용
result = learning.loc[outliers_idx,:]

# 이상치 존재 / 모델 성능에 따라 이상치 제거 결정 
visualizer.show_data(title="Battery Outliers", data=result)
# ----------------------------------------------------------------------------------------------------

====================================================================================================

# Title: Battery Outliers

====================================================================================================

# Data:

              Id   Model Manufacturer  Model_year Drivetrain  Warranty  \
2952  TRAIN_1304   IONIQ           H사           0        FWD         3
5105  TRAIN_2599   IONIQ           H사           1        FWD         3
6735  TRAIN_0030   IONIQ           H사           2        FWD         3
673   TRAIN_7088  TayGTS           P사           0        AWD         2
730   TRAIN_4715  TayGTS           P사           0        AWD         2
1975  TRAIN_0420  TayGTS           P사           0        AWD         2
2393  TRAIN_7003  TayGTS           P사           0        AWD         2
2494  TRAIN_1866  TayGTS           P사           0        AWD         2
3014  TRAIN_1721  TayGTS           P사           0        AWD         2
4042  TRAIN_0807  TayGTS           P사           0        AWD         2
4122  TRAIN_5125  TayGTS           P사           0        AWD         2
4253  TRAIN_0501  TayGTS           P사           0        AWD         2
4448  TRAIN_4779  TayGTS           P사           0        AWD         2
5279  TRAIN_0540  TayGTS           P사           0        AWD         2
5414  TRAIN_5249  TayGTS           P사           0        AWD         2
5847  TRAIN_2101  TayGTS           P사           0        AWD         2
6300  TRAIN_1478  TayGTS           P사           0        AWD         2
2503  TRAIN_4955  TayGTS           P사           0        AWD         2
2576  TRAIN_3233  TayGTS           P사           0        AWD         2
4989  TRAIN_6594  TayGTS           P사           0        AWD         2
5844  TRAIN_6383  TayGTS           P사           0        AWD         2

     Accident   Condition  Battery  Mileage   Price
2952       No  Nearly New   86.680    76186   18.64
5105       No  Nearly New   85.960    72248   20.71
6735       No  Nearly New   88.080    43412   27.53
673        No   Brand New   90.000     7405  160.78
730        No   Brand New   90.000     4281  160.86
1975       No   Brand New   90.000     8380  160.41
2393       No   Brand New   90.000        4  160.00
2494       No   Brand New   90.000     6259  160.01
3014       No   Brand New   90.000     1727  160.38
4042       No   Brand New   90.000     1764  160.05
4122       No   Brand New   90.000     9387  160.05
4253       No   Brand New   90.000     1029  160.82
4448       No   Brand New   90.000     8930  160.06
5279       No   Brand New   90.000     8993  160.12
5414       No   Brand New   90.000     3884  160.84
5847       No   Brand New   90.000     1357  160.04
6300       No   Brand New   90.000     9761  160.00
2503       No  Nearly New   79.329    38032  159.07
2576       No  Nearly New   79.329    32246  159.01
4989       No  Nearly New   79.329    32561  159.01
5844      Yes   Brand New   90.000     3773  160.00

====================================================================================================

In [4]:
# ----------------------------------------------------------------------------------------------------
# "Mileage" 컬럼의 이상치 확인 

# 이상치 인덱스 확인
outliers_idx = []
for (v1, v2, v3, v4, v5, v6, v7), group in learning.groupby([
    "Model", "Manufacturer", "Model_year",
    "Drivetrain", "Warranty", "Accident",
    "Condition"
    ]):

    group_outlier_idx = OutlierHandler(df=group).find_outliers("Mileage")

    if group_outlier_idx == []:
        pass
    else:
        outliers_idx.extend(group_outlier_idx)

# 이상치 인덱스 적용
result = learning.loc[outliers_idx,:]

# 이상치 존재 / 모델 성능에 따라 이상치 제거 결정 
visualizer.show_data(title="Mileage Outliers", data=result)
# ----------------------------------------------------------------------------------------------------

====================================================================================================

# Title: Mileage Outliers

====================================================================================================

# Data:

              Id   Model Manufacturer  Model_year Drivetrain  Warranty  \
2733  TRAIN_4206     EV6           K사           0        FWD        10
1110  TRAIN_3368     ID4           V사           0        AWD         2
4421  TRAIN_3152    ION5           H사           0        AWD         6
1991  TRAIN_0165    ION6           H사           0        AWD         9
4969  TRAIN_6401    ION6           H사           0        AWD         9
5363  TRAIN_2977      MY           T사           0        AWD         3
5733  TRAIN_6879    Q4eT           A사           0        AWD         4
1353  TRAIN_0278  RSeTGT           A사           0        AWD         7
3501  TRAIN_4015    Soul           K사           2        FWD         8
4005  TRAIN_2943    Soul           K사           2        FWD         8
5908  TRAIN_5396    Soul           K사           2        FWD         8
4677  TRAIN_2714  TayGTS           P사           1        AWD         1
4907  TRAIN_0612      eT           A사           0        AWD         0
270   TRAIN_5008      i3           B사           0        AWD         1
1903  TRAIN_0489      i3           B사           0        AWD         4
4945  TRAIN_3363      i3           B사           0        RWD         2
6568  TRAIN_0332      i3           B사           0        RWD         2

     Accident   Condition  Battery  Mileage   Price
2733      Yes   Brand New   90.000     5171   47.93
1110      Yes   Pre-Owned   60.272   199818   39.56
4421       No  Nearly New   65.739    11686   35.00
1991      Yes   Brand New      NaN     1573   38.94
4969      Yes   Brand New   90.000     9418   38.93
5363       No  Nearly New   61.153    47920   78.66
5733       No  Nearly New   69.646    10007   58.83
1353      Yes   Brand New      NaN     5391  100.00
3501       No  Nearly New   58.982    12095   23.22
4005       No  Nearly New   58.982    47369   22.85
5908       No  Nearly New   58.982    12756   23.70
4677       No  Nearly New      NaN    12173  159.89
4907      Yes   Pre-Owned   68.532   139478   70.16
270        No   Pre-Owned   46.000    54367   23.50
1903       No  Nearly New   56.000    36373   24.00
4945       No   Pre-Owned   46.000    70177   23.43
6568       No   Pre-Owned   46.000   180796   23.16

====================================================================================================

In [5]:
# ----------------------------------------------------------------------------------------------------
# "Price" 컬럼의 이상치 확인 

# 이상치 인덱스 확인
outliers_idx = []
for (v1, v2, v3, v4, v5, v6, v7), group in learning.groupby([
    "Model", "Manufacturer", "Model_year",
    "Drivetrain", "Warranty", "Accident",
    "Condition"
    ]):

    group_outlier_idx = OutlierHandler(df=group).find_outliers("Price")

    if group_outlier_idx == []:
        pass
    else:
        outliers_idx.extend(group_outlier_idx)

# 이상치 인덱스 적용
result = learning.loc[outliers_idx,:]

# 이상치 존재 / 모델 성능에 따라 이상치 제거 결정 
visualizer.show_data(title="Price Outliers", data=result)
# ----------------------------------------------------------------------------------------------------

====================================================================================================

# Title: Price Outliers

====================================================================================================

# Data:

              Id   Model Manufacturer  Model_year Drivetrain  Warranty  \
5198  TRAIN_6279     ID4           V사           0        AWD         7
2142  TRAIN_7147    ION5           H사           0        AWD         1
4734  TRAIN_6842    ION5           H사           0        AWD         1
988   TRAIN_2953    ION5           H사           0        AWD         4
2392  TRAIN_4477    ION5           H사           0        AWD         4
3529  TRAIN_1011    ION5           H사           0        AWD         4
4353  TRAIN_6814    ION5           H사           0        AWD         9
613   TRAIN_3990    ION5           H사           1        AWD         7
2461  TRAIN_5105    ION5           H사           1        AWD         7
4280  TRAIN_4407    ION5           H사           1        AWD         7
4325  TRAIN_0216    ION5           H사           1        AWD         7
6099  TRAIN_6440    ION5           H사           1        AWD         7
5737  TRAIN_6990    ION6           H사           0        AWD         1
897   TRAIN_0005    ION6           H사           0        AWD         3
4401  TRAIN_2665    ION6           H사           0        AWD         3
5502  TRAIN_5391    ION6           H사           0        AWD         3
865   TRAIN_6786    ION6           H사           0        AWD         9
6143  TRAIN_1985    ION6           H사           0        AWD         9
4217  TRAIN_7316    ION6           H사           1        AWD         7
482   TRAIN_1212      M3           T사           0        RWD         3
5023  TRAIN_3374      M3           T사           0        RWD         3
2728  TRAIN_1232      M3           T사           0        RWD         4
5332  TRAIN_1792      M3           T사           1        RWD         5
256   TRAIN_5405    Q4eT           A사           0        AWD         2
4361  TRAIN_0566    Q4eT           A사           0        AWD         2
50    TRAIN_0679    Q4eT           A사           0        AWD         4
2442  TRAIN_6906    Q4eT           A사           0        AWD         4
4617  TRAIN_7115    Q4eT           A사           0        AWD         7
5442  TRAIN_5694    Q4eT           A사           0        AWD         7
251   TRAIN_6504  RSeTGT           A사           0        AWD         3
1355  TRAIN_2010  RSeTGT           A사           0        AWD         3
3171  TRAIN_1825  RSeTGT           A사           0        AWD         8
3772  TRAIN_1640  RSeTGT           A사           0        AWD         8
4936  TRAIN_7458  RSeTGT           A사           0        AWD         8
5850  TRAIN_0167  RSeTGT           A사           0        AWD         8
4543  TRAIN_2536    Soul           K사           0        AWD        10
6279  TRAIN_4151    Soul           K사           2        AWD         8
1472  TRAIN_6103   TayCT           P사           2        AWD         0
1435  TRAIN_1385  TayGTS           P사           0        AWD         2
1720  TRAIN_4362  TayGTS           P사           0        AWD         2
2673  TRAIN_6570  TayGTS           P사           0        AWD         2
4932  TRAIN_6839  TayGTS           P사           0        AWD         2
5463  TRAIN_5614  TayGTS           P사           0        AWD         2
5770  TRAIN_0115  TayGTS           P사           0        AWD         2
6579  TRAIN_4535  TayGTS           P사           0        AWD         2
3626  TRAIN_1551      eT           A사           0        AWD         0
6087  TRAIN_7081      eT           A사           0        AWD         1
624   TRAIN_3839      eT           A사           0        AWD         3
845   TRAIN_7062      eT           A사           0        AWD         3
2039  TRAIN_0082      eT           A사           0        AWD         3
780   TRAIN_0924      eT           A사           0        AWD         4
3704  TRAIN_1206      eT           A사           2        AWD         6
968   TRAIN_5839      i3           B사           0        AWD         4
3042  TRAIN_0684      i3           B사           0        RWD         7
3926  TRAIN_2564      i3           B사           0        RWD         7
5410  TRAIN_5026      i3           B사           0        RWD         7
6288  TRAIN_5878      i3           B사           2        RWD         6
1913  TRAIN_2289      iX           B사           0        RWD         8

     Accident   Condition  Battery  Mileage   Price
5198      Yes   Brand New      NaN     4588   33.46
2142       No   Pre-Owned   53.602   156371   33.39
4734       No   Pre-Owned   53.602   148209   33.70
988        No   Pre-Owned   60.585   135277   33.83
2392       No   Pre-Owned   60.585    89470   34.12
3529       No   Pre-Owned   60.585    65763   34.25
4353      Yes   Brand New      NaN     3322   35.11
613        No  Nearly New   68.479    36227   34.26
2461       No  Nearly New   68.479    21723   34.18
4280       No  Nearly New   68.479    12469   34.21
4325       No  Nearly New   68.479    14013   34.54
6099       No  Nearly New   68.479    30612   34.51
5737       No   Pre-Owned   53.602    82720   36.42
897        No   Pre-Owned   58.162   103100   37.02
4401       No   Pre-Owned   58.162    51345   37.12
5502       No   Pre-Owned   58.162   102431   37.12
865        No   Brand New      NaN     6260   37.98
6143       No   Brand New      NaN     1135   37.94
4217       No  Nearly New   68.479    34099   36.89
482        No  Nearly New   61.153    39319   53.26
5023       No  Nearly New   61.153    15418   53.50
2728       No  Nearly New   63.701    43882   53.68
5332       No  Nearly New   66.355    38934   53.04
256        No   Pre-Owned   64.186   123350   57.26
4361       No   Pre-Owned   64.186    77207   56.95
50         No  Nearly New   69.646    28815   58.12
2442       No  Nearly New   69.646    32833   58.25
4617       No   Brand New      NaN     1706   59.04
5442       No   Brand New      NaN      944   59.05
251        No  Nearly New   78.227    23780  100.06
1355       No  Nearly New   78.227    16987   99.82
3171       No   Brand New      NaN     5779  101.15
3772       No   Brand New      NaN     1452  101.19
4936       No   Brand New      NaN     8342  101.01
5850       No   Brand New      NaN     4058  101.01
4543       No   Brand New      NaN     3473   18.41
6279       No  Nearly New   58.982    24605   21.95
1472       No  Nearly New   76.093    27067  120.02
1435       No  Nearly New   76.156    26106  159.88
1720       No  Nearly New      NaN    29719  159.61
2673       No  Nearly New      NaN    23418  159.68
4932       No  Nearly New   76.156    25014  159.75
5463       No  Nearly New      NaN    44186  159.86
5770       No  Nearly New   76.156    11401  159.71
6579       No  Nearly New      NaN    19664  159.87
3626      Yes   Pre-Owned   68.532    69741   69.81
6087       No   Pre-Owned   71.388   112071   71.88
624        No  Nearly New   77.460    21404   73.19
845        No  Nearly New   77.460    46576   73.12
2039       No  Nearly New   77.460    15126   73.26
780        No  Nearly New   80.688    22874   72.89
3704       No  Nearly New   87.552    37455   73.87
968        No  Nearly New   56.000    30304   23.31
3042       No   Brand New      NaN     8895   24.32
3926       No   Brand New      NaN     3626   24.16
5410       No   Brand New      NaN     8236   24.07
6288       No  Nearly New   56.000    20562   22.91
1913      Yes   Brand New      NaN     8342   78.92

====================================================================================================